### ISSUE TITLE
A question for adding functions

### ISSUE THREAD

**Issue by ilovefood2** [KryptonB/inventory-management-system#2]
I just tried and it seems working fine, but I'm looking for a way to add bar code scanner function, and adding a page that display individual item properties if that item is clicked, any idea how to add those features? 

many thanks

**Comment by ilovefood2** [comment]
In the meantime, can you explain a little about each sections/files ? what if someone wants to customized it, where should start from?

**Comment by ilovefood2** [comment]
sorry, I just wonder if you could add bar code scanner feature too

**Comment by KryptonB** [comment]
Hi, Sorry I was busy with some work. So couldn't reply earlier.
Yes in fact adding barcode functionality is not that difficult. All you need to do is create a form text field and click on it to get the cursor inside that text box and then scan the barcode using your device.

Below are some links which will be handy for you to read on that. And you can add it to your scripts if you follow these instructions.
[stackoverflow](https://stackoverflow.com/questions/8465839/integrating-barcode-scanner-into-php-application)

[a more detailed article](https://medium.com/@chensformers/inventory-management-system-with-barcode-scanner-in-php-a-definitive-guide-d18fdc165511)

**Comment by KryptonB** [comment]
And sure, I will try to add some documentation to the major sections. In the mean time, you will be able to decode most of the code as I have added comments to all scripts to explain the core logic of important steps.

**Comment by ilovefood2** [comment]
thank you for the excellent work, I am checking some codes giving my best try since I have no prior knowledge on php/js and frontend in general.

**Comment by KryptonB** [comment]
Thanks :) 
PHP is not that difficult once you understand the basic syntax. I would recommend Brad Traversy's youtube videos as a start. Check out his below video series where he explains the basics. 
[PHP front to back series](https://www.youtube.com/watch?v=oJbfyzaA2QA&list=PLillGF-Rfqbap2IB6ZS4BBBcYPagAjpjn) - Please note that this video series does not cover the OOP approach of PHP though but it should get you up to speed with fundamentals.  

And refer [this video](https://www.youtube.com/watch?v=kEW6f7Pilc4) to learn the PDO section which is the latest database access component used in PHP (if you want, you can use MySQLi modules instead of PDO modules but I would recommend using PDO as it has more support for many different database systems.

**Comment by ilovefood2** [comment]
thank you for the info. i will check it

**Comment by ilovefood2** [comment]
in addition, the search page runs with select * from database , if table is hudge, it will take a little time to get result, do u know what is the practice way to speed it up?   I'm thinking to read certain number of entries each time using "limit #" in select clause, but don't know how it should be implemented that way.

**Comment by KryptonB** [comment]
Well... using select * queries does not necessarily slow down as long as you use it against a unique key column or a column which is already indexed. The reason I used select * in the code is because I need to be able to access all those columns from the result set (if you only need one column, then it makes sense to change the query to retrieve that column and I totally agree.)

And using LIMIT in your queries is also not a recommended practice anymore because it usually adds overhead on the server and also usually MySQL adds an implicit LIMIT clause internally if you are querying against a unique column (if I'm not mistaken).

In addition, there are many other industry best-practices you can employ to speed up your DB queries in MySQL. Check out [this article](https://www.cloudways.com/blog/mysql-performance-tuning/) which covers some very popular methods.

**Comment by KryptonB** [comment]
Regarding the plugin...
The files can be found inside vendor/DataTables folder.
It is an Open source plugin. See [their website](https://datatables.net/) for more details on how to customize. It's pretty easy to use

**Comment by ilovefood2** [comment]
thank you, i will study that

**Comment by KryptonB** [comment]
Closing the ticket as the requested details are given
